name: yalp_core
description: A starting point for Dart libraries or applications.
version: 1.0.1
repository: https://github.com/bierbaumtim/yalp/tree/master/yalp_core
issue_tracker: https://github.com/bierbaumtim/yalp/issues
homepage: https://github.com/bierbaumtim/yalp

environment:
  sdk: ">=3.4.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  stack_trace: ^1.12.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
