name: yalp_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/bierbaumtim/yalp/tree/master/yalp_core
issue_tracker: https://github.com/bierbaumtim/yalp/issues
homepage: https://github.com/bierbaumtim/yalp

environment:
  sdk: ">=3.4.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  stack_trace: ^1.11.1
  uuid: ^4.4.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
